### ISSUE TITLE
KIE Sandbox docker-compose with access to github

### ISSUE THREAD

**Issue by merlosy** [apache/incubator-kie-issues#1776]
**Context**

I'm trying to run a local kie sandbox instance based on the latest docker images.
So far, it looks like below:
```yml
services:

    kie-sandbox-extended-services:
        container_name: kie-sandbox-extended-services
        image: apache/incubator-kie-sandbox-extended-services:10.0.0
        ports:
            - 21345:21345

    cors-proxy:
        container_name: cors-proxy
        image: apache/incubator-kie-cors-proxy:10.0.0
        environment:
            # see https://github.com/apache/incubator-kie-tools/tree/main/packages/cors-proxy
            - "CORS_PROXY_HTTP_PORT=8090"
            - "CORS_PROXY_ORIGIN=*"
            - "CORS_PROXY_VERBOSE=false"
        ports:
            - 8081:8080

    kie-sandbox:
        container_name: kie-sandbox
        image: apache/incubator-kie-sandbox-webapp:10.0.0
        depends_on:
            - kie-sandbox-extended-services
            - cors-proxy
        environment:
            - "KIE_SANDBOX_EXTENDED_SERVICES_URL=http://localhost:21345"
            - "CORS_PROXY_URL=http://localhost:8081"
        ports:
            - 8090:8080
```
- It successfully run and open the sandbox on localhost:8090.
- I can add a github personal access token

**Issue**

When adding the URL of the private repository, I get the following error: "Can't determine Git refs for 'https://github.com/merlosy/xxxxxx'".
Is there anything I might be missing?

**Comment by tiagobento** [comment]
The CORS proxy URL is configured via KIE_SANDBOX_CORS_PROXY_URL instead of just CORS_PROXY_URL.

**Comment by thiagoelg** [comment]
I think the issue is with: `- "CORS_PROXY_HTTP_PORT=8090"`

This environment variable maps the CORS Proxy service running inside the container to the 8090 port, but the exposed (and mapped) port is actually 8080.

Those env vars are not necessary when running inside a container, so I would remove them and try again:

```yml
services:

    kie-sandbox-extended-services:
        container_name: kie-sandbox-extended-services
        image: apache/incubator-kie-sandbox-extended-services:10.0.0
        ports:
            - 21345:21345

    cors-proxy:
        container_name: cors-proxy
        image: apache/incubator-kie-cors-proxy:10.0.0
        ports:
            - 8081:8080

    kie-sandbox:
        container_name: kie-sandbox
        image: apache/incubator-kie-sandbox-webapp:10.0.0
        depends_on:
            - kie-sandbox-extended-services
            - cors-proxy
        environment:
            - "KIE_SANDBOX_EXTENDED_SERVICES_URL=http://localhost:21345"
            - "KIE_SANDBOX_CORS_PROXY_URL=http://localhost:8081"
        ports:
            - 8090:8080
```

Check out our docker-compose here: https://github.com/apache/incubator-kie-tools/blob/10.0.x/packages/kie-sandbox-distribution/docker-compose.yaml (ignore the `KIE_SANDBOX_DISTRIBUTION__*` variables, as they are replaced during build).

_Edit: Also, the `CORS_PROXY_URL` env var is wrong, use KIE_SANDBOX_CORS_PROXY_URL, as @tiagobento mentioned._

**Comment by merlosy** [comment]
Thanks for the quick response @tiagobento end @thiagoelg !

I did the upgrades as you suggested, also updated the syntax for environment variables (based on your docker-compose):

```yml
services:

    kie-sandbox-extended-services:
        container_name: kie-sandbox-extended-services
        image: apache/incubator-kie-sandbox-extended-services:10.0.0
        ports:
            - 21345:21345

    cors-proxy:
        container_name: cors-proxy
        image: apache/incubator-kie-cors-proxy:10.0.0
        ports:
            - 8081:8080

    kie-sandbox:
        container_name: kie-sandbox
        image: apache/incubator-kie-sandbox-webapp:10.0.0
        depends_on:
            - kie-sandbox-extended-services
            - cors-proxy
        environment:
            KIE_SANDBOX_EXTENDED_SERVICES_URL: "http://localhost:21345"
            KIE_SANDBOX_CORS_PROXY_URL: "http://localhost:8081"
        ports:
            - 8090:8080
```
But, the issue persists.
Could it be related to the permissions associated with the PAT? What would be the minimal set to make it work? I tried with the ones below:

![Image](https://github.com/user-attachments/assets/53ed4866-6eed-4b09-9b25-1dbc586b9d18)

**EDIT:** probably not a token issue since it works with the _live_ version of the application

![Image](https://github.com/user-attachments/assets/fb181423-1d33-46ff-81c5-0c160a38fc98)
