### ISSUE TITLE
Configure separate token-credentials-id for use with buildchain

### ISSUE THREAD

**Issue by jstastny-cz** [apache/incubator-kie-issues#600]
Adding a new configuration option to specify in branch.yaml config, like:

```
buildchain_config:
  git:
    repository: incubator-kie-kogito-pipelines
    file_path: .ci/pull-request-config.yaml
    # the new one
    token_credentials_id: a-token
```
It will be used in Jenkinsfile.buildchain which is used across repositories.
